### ISSUE TITLE
shader doesn't works in nether

### ISSUE THREAD

**Issue by ipiiia** [Eldeston/Super-Duper-Vanilla#10]
```
[21:10:42] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:236) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:94) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:221) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:639) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.minecraft.class_310.handler$dah000$iris$resetPipeline(class_310.java:16990) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_18097(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1481(class_310.java:2144) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11117(class_634.java:940) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11782(class_2724.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11054(class_2724.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$bfb000$redirectExecuteTask(class_1255.java:521) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1085) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile FRAGMENT shader for program composite1.fsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:78) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.18.2-1.2.5.jar:?]
	... 27 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:40) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:21) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:76) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:49) ~[iris-mc1.18.2-1.2.5.jar:?]
	at net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:232) ~[iris-mc1.18.2-1.2.5.jar:?]
	... 27 more


```

M1mac / 1.18.2 / iris 1.2.5 / SDV1.2.9

**Comment by Eldeston** [comment]
Is this the full log?

**Comment by Eldeston** [comment]
Also, try using the latest commit and see if the problem still persists.
https://github.com/Eldeston/Super-Duper-Vanilla/archive/refs/heads/master.zip

**Comment by ipiiia** [comment]
> Also, try using the latest commit and see if the problem still persists.
> https://github.com/Eldeston/Super-Duper-Vanilla/archive/refs/heads/master.zip

It's working
